### ISSUE TITLE
xocl module is not loaded after installing the XRT package

### ISSUE THREAD

**Issue by haeseung81** [Xilinx/XRT#481] opened 2018-10-05 21:42 UTC
xocl module is not loaded after installing the XRT package 
You have to manually load the xocl module.

**Comment by mamin506** [comment] 2018-10-10 21:11
Hi @haeseung81,
In my test, this issue should be fixed in the latest code. Could you double check?

**Comment by stsoe** [comment] 2018-11-30 18:36
If problem still persists, then please file a CR and provide STR

**Comment by rradjabi** [comment] 2019-01-03 18:14
@haeseung81 please close this if the issue is stale and won't be tested further.

**Closed** 2019-01-03 18:17 UTC
