### ISSUE TITLE
Bandwidth kernel validation fails

### ISSUE THREAD

**Issue by vkomenda** [Xilinx/XRT#6105] opened 2022-01-03 17:15 UTC
I have a failure of the "Bandwidth kernel" test as follows.

```
$ xbutil validate -d 0000:42:00.1 --verbose -r "Bandwidth kernel"
Verbose: Enabling Verbosity
Starting validation for 1 devices

Validate Device           : [0000:42:00.1]
    Platform              : xilinx_u55n_gen3x4_xdma_base_1
    SC Version            : 7.1.12
    Platform ID           : 9964C19C-DB53-EB6C-69B6-FD2072401583
-------------------------------------------------------------------------------
Test 1 [0000:42:00.1]     : Bandwidth kernel 
    Description           : Run 'bandwidth kernel' and check the throughput
    Xclbin                : /opt/xilinx/firmware/u55n/gen3x4-xdma/base/test/bandwidth.xclbin
    Testcase              : /opt/xilinx/xrt/test/kernel_bw.exe
    Error(s)              : Found Platform
                            Platform Name: Xilinx
                            INFO: Reading
                            /opt/xilinx/firmware/u55n/gen3x4-xdma/base/test/bandwidth.xclbin
                            Loading:
                            '/opt/xilinx/firmware/u55n/gen3x4-xdma/base/test/bandwidth.xclbin'
                            Trying to program device xilinx_u55n_gen3x4_xdma_base_1
                            Device program successful!
                            XRT build version: 2.13.0
                            Build hash: c7ed990038f1bfa3b53b71385295b7635cdf08e9
                            Build date: 2022-01-03 13:49:56
                            Git branch: fix-dkms-driver-compilation
                            PID: 21292
                            UID: 1000
                            [Mon Jan  3 17:14:04 2022 GMT]
                            HOST: noether
                            EXE: /opt/xilinx/xrt/test/kernel_bw.exe
                            [XRT] ERROR: unable to sync BO: Input/output error
                            [XRT] ERROR: unable to sync BO: Input/output error
                            terminate called after throwing an instance of '[XRT]
                            ERROR: Operation failed due to earlier error 'unable to
                            sync BO: Input/output error'xrt_xocl::error'
                            
                              what():  event 5 never submitted
    Test Status           : [FAILED]
-------------------------------------------------------------------------------
Validation failed
```

`dmesg` output
```
...
[11863.932798] xocl:xdma_xfer_fastpath: Wait for request timed out
[11863.932806] xocl:xdma_xfer_fastpath: Wait for request timed out
[11863.932804] xocl:engine_reg_dump: 0-H2C0-MM: ioread32(0x00000000a3497aa0) = 0x1fc00006 (id).
[11863.932815] xocl:engine_reg_dump: 0-H2C1-MM: ioread32(0x000000003a66a58c) = 0x1fc00106 (id).
[11863.932817] xocl:engine_reg_dump: 0-H2C0-MM: ioread32(0x00000000579efa37) = 0x00000001 (status).
[11863.932822] xocl:engine_reg_dump: 0-H2C0-MM: ioread32(0x00000000f15cda8f) = 0x00f83e1f (control)
[11863.932824] xocl:engine_reg_dump: 0-H2C1-MM: ioread32(0x00000000381a3ef9) = 0x00000001 (status).
[11863.932827] xocl:engine_reg_dump: 0-H2C0-MM: ioread32(0x0000000021389e02) = 0xfffc0000 (first_desc_lo)
[11863.932829] xocl:engine_reg_dump: 0-H2C1-MM: ioread32(0x0000000075ab0183) = 0x00f83e1f (control)
[11863.932831] xocl:engine_reg_dump: 0-H2C0-MM: ioread32(0x000000001d75168c) = 0x00000000 (first_desc_hi)
[11863.932834] xocl:engine_reg_dump: 0-H2C1-MM: ioread32(0x00000000ff4018b4) = 0xfff80000 (first_desc_lo)
[11863.932835] xocl:engine_reg_dump: 0-H2C0-MM: ioread32(0x00000000e9a4d6fb) = 0x00000001 (first_desc_adjacent).
[11863.932839] xocl:engine_reg_dump: 0-H2C1-MM: ioread32(0x000000008ec5bede) = 0x00000000 (first_desc_hi)
[11863.932840] xocl:engine_reg_dump: 0-H2C0-MM: ioread32(0x00000000eae91d1a) = 0x00000001 (completed_desc_count).
[11863.932843] xocl:engine_reg_dump: 0-H2C1-MM: ioread32(0x0000000065410bfd) = 0x00000001 (first_desc_adjacent).
[11863.932844] xocl:engine_reg_dump: 0-H2C0-MM: ioread32(0x00000000e019732e) = 0x00f83e1e (interrupt_enable_mask)
[11863.932847] xocl:engine_reg_dump: 0-H2C1-MM: ioread32(0x00000000922ca738) = 0x00000001 (completed_desc_count).
[11863.932849] xocl:check_nonzero_interrupt_status: 0000:42:00.1 xdma0 user_int_enable = 0x00001e00
[11863.932851] xocl:engine_reg_dump: 0-H2C1-MM: ioread32(0x000000001d4e7180) = 0x00f83e1e (interrupt_enable_mask)
[11863.932854] xocl:check_nonzero_interrupt_status: 0000:42:00.1 xdma0 channel_int_enable = 0x0000000f
[11863.932856] xocl:check_nonzero_interrupt_status: 0000:42:00.1 xdma0 user_int_enable = 0x00001e00
[11863.932860] xocl:check_nonzero_interrupt_status: 0000:42:00.1 xdma0 channel_int_enable = 0x0000000f
[11863.932866] xocl 0000:42:00.1: dma.xdma.u.5242880 ffff928280067010 xdma_migrate_bo: DMA failed, Dumping SG Page Table, ep addr 0
[11863.932872] xocl 0000:42:00.1: dma.xdma.u.5242880 ffff928280067010 xdma_migrate_bo: 0, 0x1c318c000
[11863.932871] xocl 0000:42:00.1: dma.xdma.u.5242880 ffff928280067010 xdma_migrate_bo: DMA failed, Dumping SG Page Table, ep addr 2000
[11863.932877] xocl 0000:42:00.1: dma.xdma.u.5242880 ffff928280067010 xdma_migrate_bo: 1, 0x442ded000
[11863.932881] xocl 0000:42:00.1: dma.xdma.u.5242880 ffff928280067010 xdma_migrate_bo: 0, 0x2c866f000
[11863.932886] xocl 0000:42:00.1: dma.xdma.u.5242880 ffff928280067010 xdma_migrate_bo: 1, 0x3cd3ef000
[11863.934790] xocl 0000:42:00.1:  ffff9282181760d0 _kds_fini_client: Client pid(21292) has 3 opening context
[11863.934795] xocl 0000:42:00.1:  ffff9282181760d0 kds_del_context: Client pid(21292) del context CU(0xffffffff)
[11863.934797] xocl 0000:42:00.1:  ffff9282181760d0 kds_del_context: Client pid(21292) del context CU(0xffffffff)
[11863.934808] xocl 0000:42:00.1:  ffff9282181760d0 kds_del_context: Client pid(21292) del context CU(0x0)
[11863.934816] xocl 0000:42:00.1: icap.u.22020096 ffff9282419fe810 icap_unlock_bitstream: bitstream b880f292-024b-45ac-0390-564bd54dbc76 unlocked, ref=0
[11863.934821] xocl 0000:42:00.1:  ffff9282181760d0 xocl_destroy_client: client exits pid(21292)
[11863.934824] xocl 0000:42:00.1:  ffff9282181760d0 xocl_drvinst_close: CLOSE 3
[11864.872839] xocl 0000:42:00.1:  ffff9282181760d0 xocl_destroy_client: client exits pid(21291)
[11864.872853] xocl 0000:42:00.1:  ffff9282181760d0 xocl_drvinst_close: CLOSE 2
[11864.872858] xocl 0000:42:00.1:  ffff9282181760d0 xocl_drvinst_close: NOTIFY 00000000199e120c
```

**Comment by vkomenda** [comment] 2022-01-06 17:05
This issue arises in the current master. Same output on 5.10, 5.11, 5.15. The latter requires a patch #6092 for kernels 5.14+. It's possibly a regression because 2.12.427 works fine.

**Comment by houlz0507** [comment] 2022-01-06 18:39
Hi Vkomenda, I am not able to reproduce this failure on my test machine. Could you please do a cold reboot. Then re-run the test and send the entire dmesg?

Thanks,
Lizhi

**Comment by vkomenda** [comment] 2022-01-07 14:23
> Hi Vkomenda, I am not able to reproduce this failure on my test machine. Could you please do a cold reboot. Then re-run the test and send the entire dmesg?
> 
> Thanks, Lizhi

Hi Lizhi. Are you on Discord? Can you give me your handle?

**Comment by houlz0507** [comment] 2022-01-07 16:51
> > Hi Vkomenda, I am not able to reproduce this failure on my test machine. Could you please do a cold reboot. Then re-run the test and send the entire dmesg?
> > Thanks, Lizhi
> 
> Hi @houlz0507. Are you on Discord? Can you give me your handle?

I am not on Discord. Could you e-mail the dmesg log to lizhih@xilinx.com?
It sounds this issue reproduces on you machine these steps?
    1. cold reboot
    2. xbutil validate -d 0000:42:00.1 --verbose -r "Bandwidth kernel"

**Comment by houlz0507** [comment] 2022-01-13 01:39
@vkomenda , are you still seeing this issue with above 2 steps? If yes, could you send me the dmesg by e-mail? Thanks.

**Comment by vkomenda** [comment] 2022-01-13 12:09
> @vkomenda , are you still seeing this issue with above 2 steps? If yes, could you send me the dmesg by e-mail? Thanks.

Sure, I recompiled the latest master and had the same error. I emailed the log to you.

**Comment by houlz0507** [comment] 2022-01-13 20:14
@vkomenda, this might be shell related. And I noticed you are using "xilinx_u55n_gen3x4_xdma_base_1" which is old. Could you try "xilinx_u55n_gen3x4_xdma_base_2" shell?

**Comment by uday610** [comment] 2022-06-07 01:44
Is this still issue? otherwise, please consider closing this. Thanks

**Closed** 2022-06-07 11:07 UTC

**Comment by keryell** [comment] 2022-06-21 01:05
I have noticed on my U50 that I cannot pass the test with more than 4KiB. Can you try with adding `--run dma --param dma:block-size:4096`?
